### ISSUE TITLE
No LICENSE. MIT?

### ISSUE THREAD

**Issue by metaskills** [jakejscott/rust-parameters-lambda-extension#1]
Did not see one here so thought I would ask.

**Comment by jakejscott** [comment]
This was mostly just a experiment. Happy to use MIT :)

**Comment by jakejscott** [comment]
It's also not complete, the stuff in the README was me trying to think how it could work

**Comment by metaskills** [comment]
Thanks! I made a PR for the license. I'll open other issues with some feature requests/ideas.

**Comment by jakejscott** [comment]
@metaskills Sounds good
